services:
  mariadb:
    image: mariadb:10.11
    container_name: orangehrm-database
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=orangehrm
      - MYSQL_USER=orangehrm
      - MYSQL_PASSWORD=admin123
    volumes:
      - mariadb_data:/var/lib/mysql

  orangehrm:
    image: orangehrm/orangehrm:latest
    container_name: orangehrm-web
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    volumes:
      - orangehrm_data:/var/www/html

volumes:
  mariadb_data:
  orangehrm_data:
